### PR TITLE
add conda-forge to the ideas page

### PR DESCRIPTION
**Pull request by ocefpaf**
@MridulS I believe I got it right now. I had to delete my old fork and fork it again. Please ignore https://github.com/quantshah/gsoc/pull/1

### CODE REVIEW

**Comment by henrykironde** [comment]
@ocefpaf Could you remove the auto generated comment part.

**Comment by ocefpaf** [comment]
> Could you remove the auto generated comment part.

Done!

**Comment by henrykironde** [comment]
Thanks for the changes @ocefpaf.

**Comment by ocefpaf** [comment]
Thanks!

**Pull request merged**
