### PR TITLE
Add SciML

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Review by henrykironde — CHANGES_REQUESTED** [review]
please update the README file too. Also make sure you fill in the spreadsheet that was sent to through the mailing list

**Comment by ChrisRackauckas** [comment]
What in the README file needs to be updated?

**Comment by ChrisRackauckas** [comment]
Where is the spreadsheet? None was sent this year.

**Comment by henrykironde** [comment]
@ChrisRackauckas check your LinkedIn, I sent you the link

**Comment by ChrisRackauckas** [comment]
Done

**Review by henrykironde — APPROVED** [review]

**Comment by henrykironde** [comment]
@ChrisRackauckas, after a final review of the projects, we recommend utilizing either 175 hours or 350 hours, depending on the selected subtasks. For accountability, consider placing the larger value first and enclosing the smaller one in parentheses, for instance, 350h (can be scaled to 175h).

**Pull request merged**
