### PR TITLE
Link to FluxML projects list

### PR DESCRIPTION
**Pull request by ToucheSir**
cc @darsnack and @jpsamaroo.

### CODE REVIEW

**Review by henrykironde — CHANGES_REQUESTED** [review]
@ToucheSir could you please update the contents of the README file for this project.

**Comment by ToucheSir** [comment]
@henrykironde what did you want updated in the README? The link there is already the same as the one in this PR.

**Comment by henrykironde** [comment]
@ToucheSir we have not got any feedback from you about the slots for this project. Please check your google groups. Today is the deadline to rank the proposals on our end

**Comment by darsnack** [comment]
I've submitted Form B requesting 0 min and 0 max slots. We cannot fill out Form A because of the issue @ToucheSir mentioned.

**Comment by henrykironde** [comment]
@darsnack, thank you, that is all we need. @ToucheSir I am unable to manually review all the received proposals to determine which organization each proposal is for. Form B provides us with the total number of submissions, while form A allows us to search for the users associated with a particular proposal.

**Comment by ToucheSir** [comment]
I'm surprised Google does not provide any way (online or via data export) to see a simple count of how many proposals each org received. Either way, thanks @darsnack !

**Pull request merged**
