### PR TITLE
Request to add myself to the list of Julia mentors

### PR DESCRIPTION
**Pull request by acroy**
I would be happy to mentor a GSoC project for [JuliaQuantum](http://juliaquantum.github.io) - an organization for developing Julia libraries related to quantum science. See also JuliaQuantum/JuliaQuantum.github.io#20 for discussions of the project proposal.

### CODE REVIEW

**Comment by r-gaia-cs** [comment]
@acroy let me know if you have questions.

**Comment by acroy** [comment]
@r-gaia-cs Thanks! I certainly will come back to you once we are ready to submit the proposal.

**Comment by acroy** [comment]
@r-gaia-cs When and how do we have to score the projects? Should we assign ourselves as mentor to a project  on melange?

**Comment by r-gaia-cs** [comment]
> When and how do we have to score the projects?

@acroy You already can score the projects.

> Should we assign ourselves as mentor to a project on melange?

Yes.

**Comment by acroy** [comment]
> > When and how do we have to score the projects?
> You already can score the projects.

Am I right that we are supposed to only score the project for which we are nominated as a mentor? In your email to julia-users you linked to a document, where it says the score ranges from 0-3 stars, right?

Cc: @sbromberger, @mjsottile

**Comment by moorepants** [comment]
@acroy All of the Julia mentors should score the Julia related proposals. You all can decide then how many you'd like to accept. Once you have an idea of the # you want to accept, let Raniere know that number and he'll tally up all the requests from the sub-orgs and submit a final request to Google. We have no idea how many slots they'll provide. Typically only 2 slot per new mentoring org have been awarded, but we may luck out and get more because we are an umbrella org.

**Comment by moorepants** [comment]
BTW, you don't have to score anything. You can simply discuss who you'd like to accept for Julia. The Melange system provides a scoring system to help if you want to use it. For groups with many applications this is often useful but for small # of apps it may be overkill.

**Comment by acroy** [comment]
@moorepants Thanks for the explanation! I guess we should start the discussions then :-)

**Pull request merged**
