### PR TITLE
Add ideas list for PyBaMM

### PR DESCRIPTION
**Pull request by Saransh-cpp**

### CODE REVIEW

**Review by henrykironde — APPROVED** [review]

**Comment by henrykironde** [comment]
Done @Saransh-cpp

**Comment by Saransh-cpp** [comment]
Thanks @henrykironde!

**Comment by henrykironde** [comment]
@Saransh-cpp we sent you a spread sheet using the NumFOCUS emailing list, please complete the information needed for the application.

**Comment by brosaplanella** [comment]
Haven't received it either (or if I have I missed it)

**Pull request merged**
