### PR TITLE
Update ideas-list.md for Gridap project

### PR DESCRIPTION
**Pull request by fverdugo**
Dear Numfocuss,

I included the link to the ideas list for the Gridap project for GSOC 2024.

Kind regards,
Francesc

### CODE REVIEW

**Review by henrykironde — CHANGES_REQUESTED** [review]
Update the README

**Comment by henrykironde** [comment]
And don't forget to fill in the spread sheet sent in the email

**Comment by fverdugo** [comment]
Hi @henrykironde 

thanks for the comments.

Which email do you mean? 

"[NF GSOC-Mentors] GSOC 2024 Applications Open - Action Required". This one? 

I cannot find any spread sheet attached.

**Comment by fverdugo** [comment]
@henrykironde I updated the README

**Comment by henrykironde** [comment]
Forwarded you and email [f.verdugo.rojano@vu.nl](mailto:f.verdugo.rojano@vu.nl)

**Comment by fverdugo** [comment]
@henrykironde thanks.

I have fill in the spread sheet.

Is something else we need to do?

**Pull request merged**
