### PR TITLE
Add Open Science Labs project ideas for GSoC2024

### PR DESCRIPTION
**Pull request by xmnlab**
Dear all, 

this PR aims to add Open Science Labs project ideas link.
It was already discussed with Henry.

Thanks, appreciate that.

### CODE REVIEW

**Comment by xmnlab** [comment]
@henrykironde , a friendly reminder about this PR.
thanks!

**Comment by MridulS** [comment]
Could you also update the link at https://github.com/numfocus/gsoc?tab=readme-ov-file#open-science-labs ? Thanks!

**Comment by xmnlab** [comment]
sure. I am working on that no .. thanks for the review @MridulS

**Comment by xmnlab** [comment]
@MridulS , changes applied. thanks!

**Comment by Saransh-cpp** [comment]
Hi @MridulS @henrykironde, could you please forward us the GSoC mentor registration form for NumFOCUS? I think we missed that and a few of our organisation members haven't been added to the organisation on Google's portal. Thank you!

**Comment by henrykironde** [comment]
@Saransh-cpp can you send us an email so that we forward the form. CC all the mentors in your group.

**Pull request merged**
