### PR TITLE
Update team.md

### PR DESCRIPTION
**Pull request by jcrist**
Add my melange profile.

### CODE REVIEW

**Comment by moorepants** [comment]
thanks

**Comment by r-gaia-cs** [comment]
@jcrist I still getting

> Anonymous connections are not supported at this time. Please provide usernames of users with profiles only.

Could you go to https://www.google-melange.com/gsoc/homepage/google/gsoc2015, create a profile (**you need to create a profile** even if you participate in a previous edition of GSoC) and send me a note?

**Comment by jcrist** [comment]
Woops, I thought because `login` worked, I was all set. Profile is created. Sorry about that.

**Comment by r-gaia-cs** [comment]
> Woops, I thought because `login` worked, I was all set. Profile is created. Sorry about that.

Thanks. You should received a email with the invitation to join NumFOCUS
organization.

**Pull request merged**
