### PR TITLE
draft of juliaopt SCIP project proposal

### PR DESCRIPTION
**Pull request by mlubin**
@joehuchette, okay to list you as a possible mentor?

CC @IainNZ @tkelman @madeleineudell

We have more projects to propose in the pipeline.

### CODE REVIEW

**Comment by tkelman** [comment]
lgtm. I was going to ask why the phrasing "Google itself" but then remembered this is for gsoc.

**Comment by IainNZ** [comment]
lgtm

**Comment by madeleineudell** [comment]
lgtm

On Sat, Jan 30, 2016 at 8:31 PM, Iain Dunning <notifications@github.com>
wrote:

> lgtm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numfocus/gsoc/pull/61#issuecomment-177386264>.
>



-- 
Madeleine Udell
Postdoctoral Fellow at the Center for the Mathematics of Information
California Institute of Technology
*https://courses2.cit.cornell.edu/mru8
<https://courses2.cit.cornell.edu/mru8>*
(415) 729-4115

**Comment by joehuchette** [comment]
Looks great, you can definitely put me down as a potential mentor.

**Comment by rgaiacs** [comment]
@mlubin Thanks. I wish I was eligible to be a student for this proposal.

**Comment by mlubin** [comment]
@rgaiacs, thanks for commit access. Is it worth adding another proposal? What are the chances that we get two students?

**Comment by pbanaszkiewicz** [comment]
@mlubin:
It's hard to tell how many students we can get this time because GSOC administration has changed.

Usually organizations could hope to get a little more slots than in former year, especially since last year NumFOCUS was a "freshman".

I think there were 3 students last year (@rgaiacs could you confirm?), so if we get in I guess we could have 3-4 slots.

It's definitely worth adding more proposals. Take a look how many there were for 2015: 1 for Julia, I think 5 for SWC and a lot more for SymPy. In 2016 so far we only have 2 proposals…

**Comment by tkelman** [comment]
More possible projects than students sounds like it would be natural to me, if we have other projects ready to propose?

**Comment by rgaiacs** [comment]
@mlubin I second @pbanaszkiewicz. Adding more proposal **worth** the work.

> What are the chances that we get two students?

This will depends of how many slots Google provide to us. More projects contribute to raise this number. I hope that we have at least one student per organization and if we have more slots it will not be problem.

**Comment by mlubin** [comment]
@madeleineudell, I'll let you take the lead on writing up a proposal related to Convex.jl.

**Comment by madeleineudell** [comment]
definitely. what's the proposal timeframe?

On Tue, Feb 2, 2016 at 6:42 AM, Miles Lubin <notifications@github.com>
wrote:

> @madeleineudell <https://github.com/madeleineudell>, I'll let you take
> the lead on writing up a proposal related to Convex.jl.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numfocus/gsoc/pull/61#issuecomment-178604614>.
>



-- 
Madeleine Udell
Postdoctoral Fellow at the Center for the Mathematics of Information
California Institute of Technology
*https://courses2.cit.cornell.edu/mru8
<https://courses2.cit.cornell.edu/mru8>*
(415) 729-4115

**Comment by mlubin** [comment]
Submissions for GSOC open on Feb 8 and close on Feb 19. Not sure what submission date @rgaiacs is aiming for.

**Comment by rgaiacs** [comment]
@madeleineudell and @mlubin Last year Google only reviews applications after the submissions close. And we can change the submission as many times as we want between Feb 8 and Feb 19. I'm planning to fill the form early and update it until Feb 19.

**Comment by madeleineudell** [comment]
Great; I'll submit a PR with ideas á la Miles by the 8th if that's ok.

On Tue, Feb 2, 2016 at 12:44 PM, Raniere Silva <notifications@github.com>
wrote:

> @madeleineudell <https://github.com/madeleineudell> and @mlubin
> <https://github.com/mlubin> Last year Google only reviews applications
> after the submissions close. And we can change the submission as many times
> as we want between Feb 8 and Feb 19. I'm planning to fill the form early
> and update it until Feb 19.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numfocus/gsoc/pull/61#issuecomment-178811232>.
>



-- 
Madeleine Udell
Postdoctoral Fellow at the Center for the Mathematics of Information
California Institute of Technology
*https://courses2.cit.cornell.edu/mru8
<https://courses2.cit.cornell.edu/mru8>*
(415) 729-4115

**Comment by rgaiacs** [comment]
> Great; I'll submit a PR with ideas á la Miles by the 8th if that's ok.

It is OK.

**Pull request merged**
