### PR TITLE
Add FluxML to ideas list for 2023

### PR DESCRIPTION
**Pull request by darsnack**
Add FluxML back in with updated 2023 ideas list.

### CODE REVIEW

**Comment by henrykironde** [comment]
@darsnack did you send an email with the idea list before 5th?

**Comment by darsnack** [comment]
An email to NumFOCUS? No, we did not, but we haven't received any communication from anyone at NumFOCUS that this was required or that our sub-org was removed in Jan.

**Comment by MridulS** [comment]
I can merge this once Google officially announces the results next week :)

There was an email to all NumFOCUS projects on 10th Jan 2023.

**Comment by darsnack** [comment]
Okay thanks!

Do you know what email address that was sent to? I don't see any email on that date with "numfocus" in the message or matching your / @henrykironde's names. Just in case it is going to the wrong address, I'd like to correct it for future updates.

**Comment by henrykironde** [comment]
affiliated@numfocus.org

**Comment by ToucheSir** [comment]
Just seconding Kyle's observation that none of the FluxML GSoC mentors from last year received email communications from NumFOCUS about this. Last year all emails were sent to gsoc-mentors at numfocus.org, so this is the first I'm hearing of this distribution list. @logankilpatrick are you aware of this and who (if anyone) is on it on the FluxML side?

**Comment by logankilpatrick** [comment]
I didn't see the email either, @darsnack I suggest pinging Arliss to get on the list

**Comment by logankilpatrick** [comment]
@MridulS there is no issue with merging this, the project lists can be updated as much as we want during and after the project application process.

**Comment by darsnack** [comment]
Thanks, we're in contact with Arliss via email to get this fixed.

**Comment by MridulS** [comment]
@logankilpatrick the ideas list is supposed to be "frozen" after the application deadline and Google announcing the result as Google Program admins go through the ideas list. We only edit the ideas list during review period when Google admins asks us to make some adjustments (which they did this year). This has been a rule for a long time (atleast in my last 8 summers participating in GSoC). I will revert both of these commits.

**Pull request merged**
