### PR TITLE
Edit grammar and flow in README and CONTRIBUTING

### PR DESCRIPTION
**Pull request by willingc**
@r-gaia-cs @codersquid Nice work so far :sunny:

I made a few edits to the README and CONTRIBUTING docs. Mostly formatting and/or grammar. 

One other thought -- it may make sense to split CONTRIBUTING into mentor and student docs or put the student info before the mentor info.

### CODE REVIEW

**Comment by codersquid** [comment]
I like the changes and :+1: for merging them.

**Comment by codersquid** [comment]
also :+1: for having a student and mentor doc, but leave CONTRIBUTING.md as the parent since github uses it.

**Comment by r-gaia-cs** [comment]
@willingc Thanks for the pull request. Could you review 0af2f48? It is the split of CONTRIBUTING.

**Comment by willingc** [comment]
@codersquid Thanks :-) 
@r-gaia-cs Thanks and left feedback on the split of CONTRIBUTING. :+1:

**Pull request merged**
