### PR TITLE
Added proposal for a Cython API for DyND.

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
Here's my proposal for making DyND usable from Cython.

### CODE REVIEW

**Comment by moorepants** [comment]
You have ~12 hrs to the due time. You should go ahead an upload a version of this to Melange for the NumFOCUS org to make sure you have something submitted. You can edit the proposal in Melange up till 19:00 UTC.

We can merge this in whenever you and the DyND members consider it complete.

**Comment by insertinterestingnamehere** [comment]
@moorepants Thanks. I've uploaded it. I'll update the version there as this version improves.

**Comment by insertinterestingnamehere** [comment]
@mwiebe @izaid I think this is done. I've updated the version on the GSOC website too.

**Comment by izaid** [comment]
This is fine, it can be merged in.

**Pull request merged**
