### PR TITLE
DOC: update pandas logo & comments in README.md

### PR DESCRIPTION
**Pull request by jreback**
@rgaiacs 

just pandas doc updates on your README

### CODE REVIEW

**Comment by jreback** [comment]
@rgaiacs can you merge

**Comment by pbanaszkiewicz** [comment]
Merging since it doesn't seem like a harmful change.

**Comment by rgaiacs** [comment]
@jreback Could you send me a email, raniere@rgaiacs.com, with the email of all mentors for Pandas? Thanks.

**Comment by jreback** [comment]
shoyer@gmail.com
devasena.prasad@gmail.com
jeffreback@gmail.com I can be reached on my cell (917)971-6387 

    On Thursday, March 17, 2016 7:26 PM, Raniere Silva <notifications@github.com> wrote:
 

 @jreback Could you send me a email, raniere@rgaiacs.com, with the email of all mentors for Pandas? Thanks.—

**Comment by rgaiacs** [comment]
@jreback All mentors already invited. Fingers crossed for a lot of students apply to work on Pandas.

**Comment by jreback** [comment]
crossing fingers. let's see how many we get!

**Pull request merged**
