### PR TITLE
Created a page for sub orgs and moved idea lists into separate docs.

### PR DESCRIPTION
**Pull request by moorepants**
This is an attempt to generalize the ideas pages.

I moved each sub-org's ideas page into a separate document. Then I created a simple list of these pages in the original document. Finally I created a table to mimic the one at PSF [1] as an intro page to the sub-orgs, but I didn't know how to do that in markdown, so I wrote a simple html table. This may not be a great idea.

[1] https://wiki.python.org/moin/SummerOfCode/2015

### CODE REVIEW

**Comment by wking** [comment]
On Thu, Mar 12, 2015 at 01:51:45PM -0700, Jason K. Moore wrote:
> Finally I created this table…, but I didn't know how to do that in markdown, …

https://help.github.com/articles/github-flavored-markdown/#tables

**Comment by wking** [comment]
On Thu, Mar 12, 2015 at 01:51:45PM -0700, Jason K. Moore wrote:
> I moved each sub-org's ideas page into a separate document. Then I
> created a simple list of these pages in the original
> document. Finally I created this table to mimic the one at PSF [1]
> as an intro page to the sub-orgs…

Other than the HTML vs. GFM table, this all looks good to me.

**Comment by moorepants** [comment]
I couldn't figure out how to do the table design with GFM. Do you have a suggestion on having rows spanning a column or a different design that works with GFM?

**Comment by moorepants** [comment]
Ah! I had a more complicated html table that wouldn't work the GFM, but now it is actually simpe enough to work. I'll change it in a bit.

**Comment by moorepants** [comment]
I just gave it shot and it isn't clear how to translate my table to GFM. GFM is very limited and seems to only support inline markdown elements in the cells. I don't think it is that hard to copy the html row and edit for new orgs. Can we just leave it?

I am going to make that page the README for the 2015 directory.

**Pull request merged**
